<?php

/**
 * Implements hook_menu
 * @return array of menu mappings
 */
function dul_timeline_menu() {
	// return an associative (hash) array where each key 
	// represents a relative URL path to be entered by
	// an end-user.
	// The value for each key is an array that defines
	// page callbacks
	// @see hook_menu()
	$items = array(

		// you'll likely need an administrative form to 
		// create Timeline entries for easy reference
		// --
		// This entry creates a "Collection Timelines" menu entry
		// in the "Configuration" menu in the Admin Toolbar
		'admin/config/timeline' => array(
			'title' => 'Collection Timelines',
			'page callback' => 'dul_timeline_admin_overview',

			# these arguments are sent to Drupal's "user_access" hook 
			# for verification
			'access arguments' => array('administer site configuration'),

			# I typically separate 'admin' pages into their own file
			# End result: function dul_timeline_admin_overview() will
			# reside in this file (located in our module directory)
			'file' => 'dul_timeline.admin.inc',
		),

		// this entry defines a path to an admin form
		// where default (variable) settings can be defined
		'admin/config/timeline/settings' => array(
			'title' => 'Timeline Management Settings',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('dul_timeline_admin_settings'),
			'access arguments' => array('administer site configuration'),
			'file' => 'dul_timeline.admin.inc',
			'type' => MENU_DEFAULT_LOCAL_TASK,	// causes Drupal to create a tab.
		),

		# this is a standard path that represents an edit request
		# I'm using a wildcard, %dul_timeline_timeline, to represent
		# the machine_id assigned to each timeline record.
		# Drupal will look for a function (in THIS file) named
		# drupal_timeline_timeline_load($id).
		'admin/config/timeline/edit/%dul_timeline_timeline' => array(
			'page callback' => 'drupal_get_form',

			# the "loader" function noted above will return an 
			# array, object, string (your choice).
			'page arguments' => array('dul_timeline_admin_edit', 4),

			'file' => 'dul_timeline.admin.inc',
			'access arguments' => array('administer site configuration'),
			'title' => 'Edit Timeline Entry',
		),
	);

	// We need to query the database to get the existing
	// Timeline records, specifically to get the url_alias column
	// @https://api.drupal.org/api/drupal/includes!database!database.inc/function/db_select/7
	$dbResult = db_select('timeline', 't')
		->fields('t')
		->execute();

	foreach ($dbResult as $row) {
		$key = sprintf("collections/%s", $row->url_alias);
		$items[$key] = array(
			'page callback' => 'dul_timeline_timeline_page',
			'page arguments' => array(1),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
			);
	}

}

/**
 * Implements hook_theme
 */
function dul_timeline_theme() {
	return array(
		'bio' => array(
			'template' => 'bio-content',	// the file on disk will be named 'bio-content.tpl.php'
			'variables' => array('dulmaster_headshot' => NULL, 'dulmaster_name' => NULL, 'dulmaster_abstract' => NULL),
			),

		// DEFINE ENTRY for 'timeline-content'
		
	);
}

/**
 * "Loader" function for timeline record
 * when "%dul_timeline_timeline" is included in a key in 
 * the hook_menu() implementation
 * @see dul_timeline_menu()
 */
function dul_timeline_timeline_load($id) {
	if (preg_match('/^new/i') == 1) {
		// create new object (or array)
	} else {
		// fetch record from database
	}
}

/**
 * Page callback for the 'collections' menu entry
 */
function dul_timeline_timeline_page($url_alias) {
	# STEP ONE -- make sure the $catgory and $timeline are valid values.
	# if not, redirect to the 'whoops' page (defined in dul_system.module)
	# drupal_goto('whoops');

	#-------------------

	# PREAMBLE - load required files
	# @https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_get_path/7
	#--- require_once(drupal_get_path('module', 'dul_timeline')) . '/includes/connections.php';
	
	# STEP #1
	# $selectQuery = db_select('timeline','t')
	# 	->fields('t')
	#		->condition('url_alias', $url_alias);		//
	# $dbResult = $selectQuery->execute();
	# $timeline = $dbResult->fetchObject();


	# STEP #2 -- LOAD your variables
	// $myvarname = variable_get('namespace.myvarname');

	# STEP #3 -- fetch data from Google
	# contents of your current 'connections.php' go here

	# STAGE #4
	# create output using straight HTML or
	# render array elements

	// use drupal_add_css() and drupal_add_js()

	// For Debugging, use "dpm()" or "kpr()"

	$page['bio'] = array(
		'#theme' => 'bio',
		'#dulmaster_headshot' => '',
		'#dulmaster_name' => '',
		'#dulmaster_abstract' => '',
		);

	# create another entry for 'timeline-content'

	return $page;
}