<?php

/**
 * Implements hook_menu
 * @return array of menu mappings
 */
function dul_timeline_menu() {

	$items = array(

		'admin/config/timeline' => array(
			'title' => 'Collection Timelines',
			'page callback' => 'dul_timeline_admin_overview',

			'access arguments' => array('administer site configuration'),

			'file' => 'dul_timeline.admin.inc',
		),
		
		'admin/config/timeline/new' => array (
		
			'type' => MENU_LOCAL_ACTION,
			'title' => "New Timeline", 
			'access arguments' => array('administer site configuration'), 
			'page callback' => 'drupal_get_form',
			'page arguments' => array('dul_timeline_timeline_admin_form', "new"),
			'file' => 'dul_timeline.admin.inc',
		
		),

		'admin/config/timeline/settings' => array(
			'title' => 'Timeline Management Settings',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('dul_timeline_timeline_admin_settings'),
			'access arguments' => array('administer site configuration'),
			'file' => 'dul_timeline.admin.inc',
			'type' => MENU_DEFAULT_LOCAL_TASK,
		),

		
		'admin/config/timeline/edit/%dul_timeline' => array(
			'page callback' => 'drupal_get_form',

			# the "loader" function noted above will return an 
			# array, object, string (your choice).
			'page arguments' => array('dul_timeline_timeline_admin_form', 4),

			'file' => 'dul_timeline.admin.inc',
			'access arguments' => array('administer site configuration'),
			'title' => 'Edit Timeline Entry',
		),
	);
	

	$dbResult = db_select('timeline', 't')
		->fields('t')
		->execute();

	foreach ($dbResult as $row) {
		
		$key = sprintf("collections/%s/%s", $row->url_type, $row->url_slug);
		
		$items['collections'] = array(
			'page callback' => 'dul_timeline_timeline_page',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
			);
	}
	
	return $items;

}


function dul_timeline_load($tid) {

	$result = db_query('SELECT n.* FROM {timeline} n WHERE n.tid = :tid', array(':tid' => $tid));
	// select from timeline -> record based on ID

	$record = $result->fetchObject(); 

	return $record;

}


/**
 * Implements hook_theme
 */
 
function dul_timeline_theme() {
	
	return array(
		'the_timeline' => array(
			'template' => 'timeline',
			'variables' => array(
				'dulmaster_headshot' => NULL, 
				'dulmaster_name' => NULL, 
				'dulmaster_abstract' => NULL,
				'timeline_key' => NULL,
				'data_timeline' => NULL,
				'data_associatedcollections' => NULL,
				'data_people' => NULL,
				'data_corporatebodies' => NULL,
				),
			),
		);
	
}


function dul_timeline_timeline_load($tid) {
	
	if (preg_match('/^new/i', 1)) {
		// create new object (or array)
	} else {
		// fetch record from database
	}
}


/**
 * Page callback for the 'collections' menu entry
 */
function dul_timeline_timeline_page($url_type, $url_slug) {
	
	$page = array();
	
	// 
	$myResult = db_query('SELECT * FROM {timeline} WHERE url_type = :url_type AND url_slug = :url_slug', array(':url_type' => $url_type, ':url_slug' => $url_slug));
	
	//
	$myRecord = $myResult->fetchObject();
	
	$dulmaster_key = $myRecord->dulmaster_key;
	$dulmaster_num = $myRecord->dulmaster_num;
	$timeline_od = $myRecord->timeline_od;
	$collections_od = $myRecord->collections_od;
	$people_od = $myRecord->people_od;
	$corporate_od = $myRecord->corporate_od;
	
	// redirect to 404
	if($myRecord===FALSE) {
		
		drupal_goto('whoops');
		return;
	}


	// CONNECTIONS //
	
	// set timeout length
	$ctx = stream_context_create(array( 
		'http' => array( 
			'timeout' => 5 
			) 
		) 
	); 

	// set timeout fallback
	
	
	// Pull in Master Google Spreadsheet as JSON
	$url_dulmaster = "http://spreadsheets.google.com/feeds/list/" . $dulmaster_key . "/od6/public/values?alt=json&amp;callback=displayContent";
	$json_dulmaster = file_get_contents($url_dulmaster, 0, $ctx);
	$data_dulmaster = json_decode($json_dulmaster, TRUE);

	// dpm($url_dulmaster);
	
	// make variables for items in master sheet

	$dulmaster_sheetkey = $data_dulmaster['feed']['entry'][$dulmaster_num]['gsx$spreadsheetkey']['$t'];
	$dulmaster_name = $data_dulmaster['feed']['entry'][$dulmaster_num]['gsx$entityname']['$t'];
	$dulmaster_headshot = 'http://library.duke.edu/digitalcollections/media/jpg/' . $data_dulmaster['feed']['entry'][$dulmaster_num]['gsx$slug']['$t'] . '/med/' . $data_dulmaster['feed']['entry'][$dulmaster_num]['gsx$portraitimage']['$t'];
	$dulmaster_abstract = $data_dulmaster['feed']['entry'][$dulmaster_num]['gsx$abstract']['$t'];
	

	// Pull in other Google Spreadsheets as JSON

	$timeline_key = $dulmaster_sheetkey;
	
	$url_timeline = "http://spreadsheets.google.com/feeds/list/" . $timeline_key . "/" . $timeline_od . "/public/values?alt=json&amp;callback=displayContent";
	$json_timeline = file_get_contents($url_timeline, 0, $ctx);
	$data_timeline = json_decode($json_timeline, TRUE);

	$url_associatedcollections = "https://spreadsheets.google.com/feeds/list/" . $timeline_key . "/" . $collections_od . "/public/values?alt=json&amp;callback=displayContent";
	$json_associatedcollections = file_get_contents($url_associatedcollections, 0, $ctx);
	$data_associatedcollections = json_decode($json_associatedcollections, TRUE);

	$url_people = "https://spreadsheets.google.com/feeds/list/" . $timeline_key . "/" . $people_od . "/public/values?alt=json&amp;callback=displayContent";
	$json_people = file_get_contents($url_people, 0, $ctx);
	$data_people = json_decode($json_people, TRUE);

	$url_corporatebodies = "https://spreadsheets.google.com/feeds/list/" . $timeline_key . "/" . $corporate_od . "/public/values?alt=json&amp;callback=displayContent";
	$json_corporatebodies = file_get_contents($url_corporatebodies, 0, $ctx);
	$data_corporatebodies = json_decode($json_corporatebodies, TRUE);
	

	drupal_add_js('http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js', 'external');
	drupal_add_js('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js', 'external');
	drupal_add_css('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css', array('type' => 'external'));
	drupal_add_js('http://library.duke.edu/digitalcollections/media/app/js/colorbox-1.3.19/jquery.colorbox-min.js', 'external');
	drupal_add_css('http://library.duke.edu/digitalcollections/media/app/js/colorbox-1.3.19/colorbox.css', array('type' => 'external'));
	//drupal_add_css('http://library.duke.edu/digitalcollections/media/app/css/findingaids-eac.css', array('type' => 'external'));
	//drupal_add_css('http://library.duke.edu/digitalcollections/media/app/css/veriteco-timeline/timeline.css', array('type' => 'external'));
	drupal_add_css(drupal_get_path('module', 'dul_timeline') . '/css/timeline_styles.css' , array('preprocess' => FALSE));
	drupal_add_js(drupal_get_path('module', 'dul_timeline') . '/js/settings.js', array('preprocess' => FALSE));
	
	
	drupal_set_title($dulmaster_name);

	$page['timeline_content'] = array (
		'#theme' => 'the_timeline',
		'#dulmaster_headshot' => $dulmaster_headshot,
		'#dulmaster_name' => $dulmaster_name,
		'#dulmaster_abstract' => $dulmaster_abstract,
		'#timeline_key' => $timeline_key,
		'#data_timeline' => $data_timeline,
		'#data_associatedcollections' => $data_associatedcollections,
		'#data_people' => $data_people,
		'#data_corporatebodies' => $data_corporatebodies,
		);
	

	return $page;

}



